import 'package:flutter/material.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

SingleChildScrollView buildAulas(
    YoutubePlayerController _controller, bool isPortugues) {
  return SingleChildScrollView(
      child: Column(
    children: [
      Text(
        'Escolha sua aula',
        style: TextStyle(fontSize: 40),
      ),
      YoutubePlayer(
        controller: _controller,
        showVideoProgressIndicator: true,
        progressIndicatorColor: Colors.amber,
        progressColors: ProgressBarColors(
            playedColor: Colors.amber, handleColor: Colors.amberAccent),
      ),
      SizedBox(
        height: 20,
      ),
      ...buildBotoes(_controller, isPortugues),
    ],
  ));
}

List<Widget> buildBotoes(
    YoutubePlayerController _controller, bool isPortugues) {
  List<Widget> todosBotos = [];

  int aula = 1;
  if (isPortugues)
    todosIDsPlaylistAlfabeto().forEach((element) {
      todosBotos.add(botao(element, aula, _controller));
      aula++;
    });
  else
    todosIDsMatematica().forEach((element) {
      todosBotos.add(botao(element, aula, _controller));
      aula++;
    });

  return todosBotos;
}

Widget botao(String url, int numero, YoutubePlayerController _controller) {
  return Padding(
    padding: EdgeInsets.only(left: 30, right: 30),
    child: SizedBox(
      width: double.infinity,
      child: ElevatedButton(
          onPressed: () => _controller.load(url),
          child: Text('Aula número $numero')),
    ),
  );
}

List<String> todosIDsPlaylistAlfabeto() {
  return [
    'WG48Wk0Fu9Q',
    'BqZj11aL4t4',
    'WoT9HiVfLrc',
    'DRi8jYCqpaM',
    'z3CjFbjKs4w',
    'ezZsbOKhZeE',
    's_pMPmhTW5M',
    'YDgbHGR_Htw',
    'jZw9J6m8WrY',
    '2q84ACGOzVc',
    'z0J1nZEz0UM',
    'kIFgcfaz-qE',
    'nNJfVf88Fvw',
    'MC_N8o5Czsg',
    'H363QWcaOps',
    'rgYyO2rt_-U',
    '5fX1AiC5mDI',
    'zQBQVpsCABs',
    'Teo7s-PIg3g',
    'Me_wsc77gtA',
    '9SPqJ3ItuSo',
    'Xmzx7OtsnIk',
    'Vz06ONG1mLE',
    'RPRISsBbcXA',
    'Iob68TTsOTI',
    'v65Lu393KMI',
    'JIvWGgvYfWw',
    'OzVyTGlrJ78',
    'SE-5fbrjN0Q',
    'pXiUGd388-U',
    'QICWjrd1ECU',
    'Naz2rwL1H_E',
    'e6tkMsz4OgE',
    'LWj_awr17-U',
    'E2t6r0Q7ZMU',
    'wsdzl17Apgc',
    '2vzz8RJOVmE',
    'a4xzPw9w57k',
    'Ucs34BqCVQM',
    'qqQX43vCo-s',
    '9x6EcDSR0Is',
    'QYuVaix51FA',
    'VwxiEe2Y4_Q',
    'iMwOyu7UMSU',
    'tO47-6amcTE',
    'M01aAQGfLJ4',
    'e3SEcmnghG8',
    'lSlD7rKasKU',
    'HhFol9vl_Do',
    'vei-AAirI88',
    'SHP751D2oWY',
    'LIrrICWnvzY',
    'uU5_MgYY5kY',
    'o4r7toa5KZc',
    '4tHO1yzayfc',
    'bZNmLZtxTiI',
    '8hiBNqzmqcg',
    'N29WTJAn4n0',
    'iULWKgcFF5c',
    '-WnW2-zfhq4',
    '3Htu_3DGn78',
    'iHIGosm09nA',
    '-60hhPdLLKY',
    'vWYQr4CYPMg',
    'POeZ9F5yE28',
    'Z1ZZaDdLARc',
    'xUgRBuomFQ8',
    '0TRcQj4Kbik',
    '5MgWIyDiRrw',
    'jE0FPkkJ-vc',
    '1KtoneI_ECs',
    'l9uBAZG6ikg',
    'cTPhwQnYkj8',
    'OQN_IJO-jcQ',
    '3HmaAmRBLSk',
    'K3Acfw_9ams',
    'P1emm7x4EHI',
  ];
}

List<String> todosIDsMatematica() {
  return [
    'yzYMuPqYoPM',
    'oiOspHcfBho',
    '2V7V4VYKdSE',
    '902dRzOwdag',
    'QAzjLcBUUW4',
    'o-ZwxVS5ke8',
    '2om7YCXmX7Y',
    'bCwx4MIp8aU',
    '7INjJ_HkQ1I',
    'R_YpxXQDee0',
    'D04Pcq1KFmE',
    'FlaEZHad6dM',
    'nw5xesCTaTE',
    'r-KoZG97ZTI',
    'qjnJKWrVShg',
    'nmqyo8F95kM',
    'wVocndD-cVs',
    'Qbvpm1sgcOM',
    'eRhUyVm0wrg',
    'LmUbA3zvwwg',
    '_2tbC6W3jUU',
    'n5iB5Fczwhk',
    'Lh6am7iIujE',
    'HJBl14K4QWM',
    'KW0yzLzt0Gg',
    '_XAppt4b-50',
    'G2EwWV0z6HY',
    'j4nsbY-B7UI',
    'r2bTLdtvMKw',
    '-LOUAd3yZkw',
    '_-FyBj8ZTJ8',
    'GSrOC3BHjB8',
    '_a-EEBkmp5g',
    'cB9yhs9m5T8',
    'LTogJhFiiaA',
    '8FfXPxRsZBs',
    'A19e-FxSEOw',
    't9_MJUR6mlk',
    'tuuHAvoCQR4',
    'ljyeDJDg-aU',
    '3bSDDKHyMck',
    'S-TUmN3rBJ4',
    'k0juMDVM1O4',
    '7uf2ZzSJYlg',
    'nsN8jkYkUqk',
    'uxqQktXaZwU',
    '482znoBpL88',
    'JbKs5jLY9vE',
    'A6dl_gBhJ6M',
    'CqSXqYXq4XA',
    'Um2scfeyge0',
    'A2P-zOR5d6k',
    'XFNjdDRgn90',
    'LUyYQuWJ4aY',
    'jmAF0vNcNHA',
    'BGmT4TcLKkk',
    'bpHLZzCaa3I',
    'gc64m3TLoi4',
    '5X0-e8BCcL0',
    'LCaRV4UAu9I',
    's-7z_7rfCU4',
    'HNKzObz4SC4',
    '-LvsP5Nn-cA',
    'ha3UfasgzH8',
    'HNboIUgjtAo',
    'ZAuZofwMSow',
    'BpBI8fgC_y8',
    'IsQTSBJcR6M',
    'Mb1YWFMTZE0',
    '3WXO7M2iWBU',
    'or2Ae2o1j2g',
    'AM23mNKr65c',
    'Ln48UT2v8YE',
    'P0jNRfovzNg',
    '9dNMRA7nxwQ',
    'Ze7-_IXOWbg',
    '560G0oo29f4',
    'mbSiqJpKqPE',
    'RsMwlx8A_-w',
    'HPbAPoHmLFY',
    'Aw5hRB2c8dM',
    'ZBo_Mx9nLr0',
    'BMvtAAmjLNA',
    'PevC-g1lf2c',
    'UCH0m8oUfck',
    'vkxUeco2ueY',
    'f7w1ETEWKos',
    'cjQSIZrk2jE',
    'dnpzHJDVZc4',
    'sABdMmf-9AA',
    'WBpfGli-7xk',
    'Hx8AhNHun1M',
    '7-1uuQHG0Qg',
    '5CvG0kOMpu0',
    't1nJSHispF0',
    'EJsykA8GfBs',
    'Gx-lgLHVwdQ',
    'FUH1FuoybJE',
    'JPEE2zMIeB8',
    '5SeNRm4doeE',
    'BOVZHxhfYLs',
    'Oqb7Iyt6lpY',
    'smhzIX2F8Hg',
    'K3xF4WXF9Xc',
    'Z9mHp2UVozY',
    'wXx2ZLVYy1U',
    'xRX_P64UYow',
    'r8uKrucIRLM',
    'raKPjnYlvyE',
    'pjxaEOApMkE',
    'L-DCSs82SZ8',
    'JN_mYN1fk_Q',
    'Jc8nQYqTzeE',
    'KVPmWJtXCtk',
    'XZ4PiLObQOI',
    'kfvezbZwE08',
    'KSv8jHXXO7c',
    'izIGUp5lDJ0',
    '9AgGdP3m0pE',
    'OV2RBeYjMuQ',
    'Gt7biCas2XY',
    'l2knf4pE5Vo',
    'iK64aoWOj28',
    'N9f7QkZNLCc',
    'Z5GSmzsKmOU',
    'ogaHTIfZ2zI',
    'z9NupCtrjIg',
    'spDNo6sbtCI',
    'VpZBDI0Wi9E',
    'd7Y9bSnxpwI',
    'gtGUkBfAQ_4',
    'DEcRoMNdkdI',
    'OmVdA5UG6Zs',
    'JFnzwEZLEaA',
    'YX4zq0HfQkk',
    'qkVCs4jfYIg',
    '3wpKEHhSPBM',
    '3ve7Qdr8uiA',
    '6Eru1iVoCWM',
    'N6CMUEd9rQw',
    'knpciN0_Cio',
    '--2gVNJHJDs',
    '1ncx2ZzNWC8',
    '184dL9z5DfM',
    'bBOfaE_25wA',
    'SUJ3SmnD150',
  ];
}
